# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aDHQy8ZPqjZM77nTpYTCstpC7Bxp6q3w
"""

#Clase que me representa
class Gaby():
  def _init_(self, nombre, apellido, edad, hobbies, orientacion, comida favorita):
    self.nombre = "Gaby"
    self.apellido = "Gonzalez"
    self.edad = 24
    self.hobbies = "Dibujar"
    self.orientacion = "Hetero"
    self.comida_favorita = Lasaña
    pass

#Acciones favoritas
  def realizo_dibujo(self):
    print("Mi actividad favorita es dibujar en mi tiempo libre"):
  def realizo_animaciones(self):
    print("Me gusta tambien realizar animaciones"):
  def realizo_trabajo(self):
    print("Suelo ir a eventos de anime para vender mis productos"):