# -*- coding: utf-8 -*-
"""Paola.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VRL7uYj1eizyILp2T1Ztdk0kBCQxdbi_
"""

#Clase paola
class Paola():
      def __init__(self, nombre, apellido, color_favorito, hobbies, comida_favorita):
          self.nombre = nombre
          self.apellido = apellido
          self.color_favorito = color_favorito
          self.hobbies = hobbies
          self.comida_favorita = comida_favorita


      def mi_nombre(self):
          print(f"Mi nombre es: nombre = {self.nombre} y  apellido = {self.apellido}")

      def mi_color(self):
          print(f"Mi color favorito es {self.color_favorito}")

      def mi_pasatiempo(self):
          print(f"Mi actividad favorita es {self.hobbies}")

      def mi_comida(self):
          print(f"Mi comida favorita es {self.comida_favorita}")



yo= Paola("Paola","Urdiales","Morado","Dormir","Hamburguesa")
yo.mi_nombre()
yo.mi_color()
yo.mi_pasatiempo()
yo.mi_comida()